---
- name: Install automatic update handler package
  yum:
    name: dnf-automatic
    state: latest

- name: Template over automatic update handler
  template:
    src: automatic_updates.conf.j2
    dest: /etc/dnf/automatic.conf
    backup: yes

- name: Start automatic update timer
  service:
    name: dnf-automatic.timer
    state: started
    enabled: yes
