---
- name: Install Cockpit packages
  yum:
    name: "{{ cockpit_packages }}"
    state: latest

- name: Enable Cockpit Socket
  service:
    name: cockpit.socket
    state: started
    enabled: yes

- name: Enable Cockpit on Firewalld
  ansible.posix.firewalld:
    service: cockpit
    state: enabled
    permanent: yes
  notify: restart firewalld
